[package]
name = "example-matrix"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
simplealloc = { path = "../../crates/simplealloc" }
polkavm-derive = { path = "../../crates/polkavm-derive" }
