[package]
name = "game-of-life-host"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
env_logger = { version = "0.11.0", default-features = false }
polkavm = { path = "../../crates/polkavm" }
minifb = "0.27.0"
